"""共享模块 - 常量和状态键。"""

from shared.state_keys import StateKeys
from shared.constants import (
    MAX_CONCURRENT_DOCUMENTS,
    MAX_RETRY_ATTEMPTS,
    DEFAULT_PDF_DPI,
    PDF_EXTENSIONS,
    IMAGE_EXTENSIONS,
    HIGH_CONFIDENCE_THRESHOLD,
    LOW_CONFIDENCE_THRESHOLD,
)

__all__ = [
    "StateKeys",
    "MAX_CONCURRENT_DOCUMENTS",
    "MAX_RETRY_ATTEMPTS",
    "DEFAULT_PDF_DPI",
    "PDF_EXTENSIONS",
    "IMAGE_EXTENSIONS",
    "HIGH_CONFIDENCE_THRESHOLD",
    "LOW_CONFIDENCE_THRESHOLD",
]
